// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

// example response
type Example struct {
	// name of project
	ProjectName string `json:"projectName"`
	// environment code
	Envcode string `json:"envcode"`
	// API version
	Version string `json:"version"`
}

// upload mutation input
type UploadInput struct {
	// upload file data
	Data graphql.Upload `json:"data"`
}

// upload mutation output
type UploadPayload struct {
	// uploaded file path
	Path string `json:"path"`
}
