// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

// upload mutation input
type UploadInput struct {
	// upload file data
	Data graphql.Upload `json:"data"`
}

// upload mutation output
type UploadPayload struct {
	// uploaded file path
	Path string `json:"path"`
}
