# https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - unconvert
    - unused
    - whitespace

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - opinionated
  dupl:
    threshold: 50
  gocyclo:
    min-complexity: 30

issues:
  exclude-use-default: false
