name: Analysis
env:
  TZ: 'Asia/Tokyo'
on:
  pull_request:
    branches:
      - main

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Analysis
        uses: ./.github/actions/analysis
